# Program : ae.R
# Purpose : Independent QC program for SDTM AE
# Run from the P3 project root after dm.R

source("r/sdtm/setup.R")

# local coding table, no MedDRA: verbatim to preferred term
pt <- c(
  "RUNNY NOSE" = "NASOPHARYNGITIS", "NASAL CONGESTION" = "NASOPHARYNGITIS",
  "COMMON COLD" = "NASOPHARYNGITIS", "COLD" = "NASOPHARYNGITIS",
  "COUGH" = "COUGH", "SORE THROAT" = "OROPHARYNGEAL PAIN", "THROAT PAIN" = "OROPHARYNGEAL PAIN",
  "URTI" = "UPPER RESPIRATORY TRACT INFECTION",
  "UPPER RESPIRATORY INFECTION" = "UPPER RESPIRATORY TRACT INFECTION",
  "DIARRHEA" = "DIARRHOEA", "LOOSE STOOLS" = "DIARRHOEA",
  "DIZZY" = "DIZZINESS", "DIZZINESS" = "DIZZINESS",
  "BACK PAIN" = "BACK PAIN", "LOWER BACK PAIN" = "BACK PAIN",
  "RASH ON ARM" = "RASH", "SKIN RASH" = "RASH",
  "INSOMNIA" = "INSOMNIA", "TROUBLE SLEEPING" = "INSOMNIA",
  "STOMACH ACHE" = "ABDOMINAL PAIN", "ABDOMINAL PAIN" = "ABDOMINAL PAIN",
  "TOOTH ACHE" = "TOOTHACHE", "TOOTHACHE" = "TOOTHACHE",
  "APPENDICITIS" = "APPENDICITIS", "FALL WITH FRACTURE OF LEFT WRIST" = "WRIST FRACTURE")
soc <- c(
  "NASOPHARYNGITIS" = "INFECTIONS AND INFESTATIONS",
  "UPPER RESPIRATORY TRACT INFECTION" = "INFECTIONS AND INFESTATIONS",
  "APPENDICITIS" = "INFECTIONS AND INFESTATIONS",
  "COUGH" = "RESPIRATORY, THORACIC AND MEDIASTINAL DISORDERS",
  "OROPHARYNGEAL PAIN" = "RESPIRATORY, THORACIC AND MEDIASTINAL DISORDERS",
  "DIARRHOEA" = "GASTROINTESTINAL DISORDERS", "ABDOMINAL PAIN" = "GASTROINTESTINAL DISORDERS",
  "TOOTHACHE" = "GASTROINTESTINAL DISORDERS",
  "DIZZINESS" = "NERVOUS SYSTEM DISORDERS",
  "BACK PAIN" = "MUSCULOSKELETAL AND CONNECTIVE TISSUE DISORDERS",
  "RASH" = "SKIN AND SUBCUTANEOUS TISSUE DISORDERS",
  "INSOMNIA" = "PSYCHIATRIC DISORDERS",
  "WRIST FRACTURE" = "INJURY, POISONING AND PROCEDURAL COMPLICATIONS")
outcome <- c("RECOVERED/RESOLVED" = "RECOVERED/RESOLVED", "RECOVERING" = "RECOVERING/RESOLVING")

ae <- read_raw("AE") |>
  mutate(
    STUDYID = "VAXF101",
    DOMAIN = "AE",
    USUBJID = paste0("VAXF101-", SUBJECT),
    AETERM = trimws(AETERM),
    AEDECOD = unname(pt[toupper(AETERM)]),
    AEBODSYS = unname(soc[AEDECOD]),
    AECAT = "UNSOLICITED",
    AESEV = toupper(AESEV),
    AEACN = "NOT APPLICABLE",
    AEREL = toupper(AEREL),
    AEOUT = unname(outcome[toupper(AEOUT)]),
    AESTDTC = iso_date(AESTDAT),
    AEENDTC = iso_date(AEENDAT)) |>
  left_join(dm_ref(), by = "USUBJID") |>
  mutate(
    AEENRTPT = if_else(AEONGO == "Y", "ONGOING", NA_character_),
    AEENTPT = if_else(AEONGO == "Y", substr(RFPENDTC, 1, 10), NA_character_),
    EPOCH = epoch(AESTDTC, RFXSTDTC),
    AESTDY = study_day(AESTDTC, RFSTDTC),
    AEENDY = study_day(AEENDTC, RFSTDTC)) |>
  add_seq("AESEQ", c("AEDECOD", "AESTDTC"))

stopifnot(!anyNA(ae$AEDECOD), !anyNA(ae$AEBODSYS))
finalize(ae, "AE", "Adverse Events")
